#use the base package for from official pytorch source 
FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime

ENV TZ=Asia/Singapore
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install libsndfile1 (linux soundfile package)
RUN apt-get update && apt-get install -y build-essential libsndfile1 git sox wget \
&& rm -rf /var/lib/apt/lists/*

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

# Upgrade the pip
RUN pip install --upgrade pip

# Install pip requirements
RUN rm -rf $(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")/ruamel*
RUN python3 -m pip install --ignore-installed git+https://github.com/speechbrain/HyperPyYAML
ADD requirements.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# installing jupyter lab inside
RUN pip install jupyterlab

# declare port used by jupyterlab
EXPOSE 8888

# set default command for jupyterlab
CMD ["jupyter" ,"lab", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--NotebookApp.token=''", "--NotebookApp.password=''", "--allow-root"]

# declare port used by tensorboard
EXPOSE 6006

#docker container starts with bash
WORKDIR /lid
RUN ["bash"]